In [114]:
'''

What columns to focus one in each dataset:

Attack_Dataset.csv: Category, Attack Type, Target Type, Vulnerability, MTIRE Technique

cybersecurity_cases_india_combined.csv: Year, Incident_Type, Category

Global_Cybersecurity_Threats_2015-2024.csv: Year, Attack Type, Target Industry, Security Vulnerability Type

vulnerability_assessment_data.csv: Severity, Vulnerability Type, Risk Score


'''

'\n\nWhat columns to focus one in each dataset:\n\nAttack_Dataset.csv: Category, Attack Type, Target Type, Vulnerability, MTIRE Technique\n\ncybersecurity_cases_india_combined.csv: Year, Incident_Type, Category\n\nGlobal_Cybersecurity_Threats_2015-2024.csv: Year, Attack Type, Target Industry, Security Vulnerability Type\n\nvulnerability_assessment_data.csv: Severity, Vulnerability Type, Risk Score\n\n\n'

In [115]:
import pandas as pd
import numpy as np



_1_attacks = pd.read_csv('Datasets/Attack_Dataset.csv')
_2_india = pd.read_csv('Datasets/cybersecurity_cases_india_combined.csv')
_3_globald = pd.read_csv('Datasets/Global_Cybersecurity_Threats_2015-2024.csv')
_4_vulnerability = pd.read_csv('Datasets/vulnerability_assessment_data.csv')

# subset so specify only drop if these specific columns are missing
_1_attacks = _1_attacks.dropna(subset=['ID','Title','Scenario Description','Tools Used','Attack Steps ','Impact','Detection Method','Solution','Tags','Source'])
_2_india = _2_india.dropna(subset=['Day','Amount_Lost_INR','City']) # drops rows with missing data
_3_globald = _3_globald.dropna(subset=['Country', 'Financial Loss (in Million $)', 'Number of Affected Users' , 'Attack Source' , 'Defense Mechanism Used' , 'Incident Resolution Time (in Hours)'])
_4_vulnerability = _4_vulnerability.dropna(subset=['ID', 'Description', 'Affected Software' , 'Discovered Date' , 'Patch Date' , 'Description Length', 'Days to Patch'])

# _1_attacks.head()
# _2_india.head()
# _3_globald.head()
# _4_vulnerability.head()

In [116]:
# Attack_Dataset.csv: Category, Attack Type, Target Type, Vulnerability, MTIRE Technique

_1_to_drop = ['ID','Title','Scenario Description','Tools Used','Attack Steps ','Impact','Detection Method','Solution','Tags','Source']

_1_attacks.drop(columns=_1_to_drop, inplace=True)
_1_attacks.head()

,Category,Attack Type,Target Type,Vulnerability,MITRE Technique,Unnamed: 15
0,Mobile Security,SQL Injection (SQLi),"Web Login Portals (e.g., banking, admin dashbo...",Unsanitized input fields in SQL queries,"T1078 (Valid Accounts), T1190 (Exploit Public-...",NaN
1,AI Agents & LLM Exploits,SQL Injection,"Web Applications, Login Pages, Search Forms",Improperly filtered input fields that allow SQ...,T1190 – Exploit Public-Facing Application,NaN
2,AI Agents & LLM Exploits,SQL Injection,"Web Applications, Login Forms, URL Parameters,...",Error message exposure due to lack of input va...,T1190 – Exploit Public-Facing Application,NaN
3,AI Agents & LLM Exploits,SQL Injection,"Web Applications, Login Pages, Search Fields, ...","No error messages, but user input is still pas...",T1190 – Exploit Public-Facing Application,NaN
4,AI Agents & LLM Exploits,SQL Injection,"Web Applications, User Registration Forms, Pro...",Trusting previously stored unvalidated data in...,T1505.003 – SQL Injection,NaN

In [117]:
# cybersecurity_cases_india_combined.csv: Year, Incident_Type, Category

_2_to_drop = ['Day','Amount_Lost_INR','City']

_2_india.drop(columns=_2_to_drop, inplace=True)
_2_india.head()

   Year Incident_Type     Category
0  2022   Data Breach    Corporate
1  2023      Phishing  Educational
2  2021   Data Breach   E-commerce
3  2023      Phishing       Health
4  2023      Phishing   Government

In [118]:
# Global_Cybersecurity_Threats_2015-2024.csv: Year, Attack Type, Target Industry, Security Vulnerability Type


_3_to_drop = []
_3_to_drop = ['Country', 'Financial Loss (in Million $)', 'Number of Affected Users' , 'Attack Source' , 'Defense Mechanism Used' , 'Incident Resolution Time (in Hours)']

_3_globald.drop(columns=_3_to_drop, inplace=True)
_3_globald.head()

   Year        Attack Type     Target Industry Security Vulnerability Type
0  2019           Phishing           Education          Unpatched Software
1  2019         Ransomware              Retail          Unpatched Software
2  2017  Man-in-the-Middle                  IT              Weak Passwords
3  2024         Ransomware  Telecommunications          Social Engineering
4  2018  Man-in-the-Middle                  IT          Social Engineering

In [119]:
# vulnerability_assessment_data.csv: Severity, Vulnerability Type, Risk Score


_4_to_drop = []
_4_to_drop = ['ID', 'Description', 'Affected Software' , 'Discovered Date' , 'Patch Date' , 'Description Length', 'Days to Patch']

_4_vulnerability.drop(columns=_4_to_drop, inplace=True)
_4_vulnerability.head()

  Severity Vulnerability Type  Risk Score
0   Medium                XSS           5
1      Low               CSRF           2
2   Medium    Buffer Overflow          10
3     High               CSRF           5
4      Low               CSRF           4